name: "First CICD Workflow"
on:
  push:
    branches:
      -main
  
jobs:
  First-Work:
    runs-on: ubuntu-latest
  
    steps:
      - name: First steps
        run: echo "This is my first CICD workflow"
      
      - name: Second steps
        run: echo "This is my second CICD workflow"
      - name: Third steps
        run: echo "This is my third CICD workflow"