name: First Workflow

on: [push]

jobs:
  first-time-cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: echo "Checking out the repository..."

      - name: Send Email On Success
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_TO }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Workflow Succeeded"
          to: "nizamuddinnayeem22@gmail.com"
          from: "Deploy Bot <${{ secrets.MAIL_FROM }}>"
          body: |
            Hello,

            This is to inform you that the first workflow has completed successfully.

            Best regards,
            Your DevOps Team